name: wake_on_lan
description: Send wake on LAN magic packets to devices on your local network.
version: 4.1.0
homepage: https://github.com/JagandeepBrar/package-wake-on-lan
repository: https://github.com/JagandeepBrar/package-wake-on-lan
issue_tracker: https://github.com/JagandeepBrar/package-wake-on-lan/issues
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  convert: ^3.1.1
dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
